replicaCount: 1

image:
  repository: simonschneider/traefik-jwt-decode
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

env:
  PORT: "8080"
  CLAIM_MAPPING_FILE_PATH: "/claim-mappings/config.json"
  AUTH_HEADER_KEY: "Authorization"
  TOKEN_VALIDATED_HEADER_KEY: "jwt-token-validated"
  LOG_LEVEL: "info"
  LOG_TYPE: "json"
  MAX_CACHE_KEYS: "10000"
  CACHE_ENABLED: "true"
#  CLAIM_MAPPINGS: "claim1:header1"

claimMappings: |
    {}
#    {
#      "claim1": "header1",
#      "claim2": "header2"
#    }

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
