apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-jwt-decode.fullname" . }}
  labels:
    {{- include "traefik-jwt-decode.labels" . | nindent 4 }}
data:
  config.json: {{ toYaml .Values.claimMappings | indent 2 -}}
