name: Build and push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sun') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make all
      - uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.ref == 'refs/heads/master'
        with:
          name: simonschneider/traefik-jwt-decode
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.version.outputs.tag }}"
          workdir: _docker
